WebAppMVC_Assignment1/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppMVC_Assignment1.Models
{
    public class Doctor
    {
        //private double bodyTemp;
        
        public double BodyTemp { get; set; }

        public static string giveRecomendation(double patientTemp) 
        {
            string msg;

            if (patientTemp <= 80 || patientTemp >= 110)
            {
                msg = "Cannot provide any Recommendation. Please enter a valid temperature";
            }
            
            if (patientTemp > 98 && patientTemp < 110)
            {
                msg = "Recorded body temperature is "+ patientTemp+". You seem to have a fever. Consult a real Doctor!";
            }
            else 
            {
                msg = "Recorded body temperature is " + patientTemp + ". You do not have a fever";
            }

            return msg;
        }
    }
}

WebAppMVC_Assignment1/Models/GuessingGame.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppMVC_Assignment1.Models
{
    public class GuessingGame
    {
        public int Num { get; set; }


        public static int getRandomNum()
        {
            int num = 0;

            Random random = new Random();
            num = random.Next(1,100);

            return num;
        }

        public static string getResult(int usrGuessNumm, int genNum)
        {
            string msg = null;

            if (usrGuessNumm == genNum)
            {
                msg = "Perfect. You Guessed it!";
            }
            
            if (usrGuessNumm > genNum)
            {
                msg = "Oops.That was too high.Try Again!";
            }

            if (usrGuessNumm < genNum)
            {
                msg = "Oops.That was too low.Try Again!";
            }
            
            return msg;
        }

    }
}

WebAppMVC_Assignment1/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace WebAppMVC_Assignment1.Controllers
{
    public class AppController : Controller
    {
        public IActionResult About()
        {
            HttpContext.Session.SetString("View", "App/About");
            return View();
        }
        public IActionResult Contact()
        {
            HttpContext.Session.SetString("View", "App/Contact");
            return View();
        }

        public IActionResult Projects()
        {
            HttpContext.Session.SetString("View", "App/Projects");
            return View();
        }
    }
}

WebAppMVC_Assignment1/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAppMVC_Assignment1.Models;
using Microsoft.AspNetCore.Http;

namespace WebAppMVC_Assignment1.Controllers
{
    public class GameController : Controller
    {
        [HttpGet]
        public IActionResult RandomNumber()
        {
            if (HttpContext.Session.GetString("View") != null && (HttpContext.Session.GetString("View")).CompareTo("Game/RandomNumber/Post")==0)
            { 
               ViewBag.Result = HttpContext.Session.GetString("Result");
               ViewBag.UserGuess= HttpContext.Session.GetInt32("UserGuess");
               ViewBag.GeneratedNumber = HttpContext.Session.GetInt32("RandomNumber");
            }

            int generatedNumber = GuessingGame.getRandomNum();
            HttpContext.Session.SetInt32("RandomNumber", generatedNumber);

            return View();
        }


        [HttpPost]
        public IActionResult RandomNumber(int Num)
        {
            int generatedNumber = Convert.ToInt32(HttpContext.Session.GetInt32("RandomNumber"));
            String result = GuessingGame.getResult(Num, generatedNumber);

            HttpContext.Session.SetString("Result", result);
            HttpContext.Session.SetInt32("UserGuess", Num);

            HttpContext.Session.SetString("View", "Game/RandomNumber/Post");

            return RedirectToAction(nameof(RandomNumber)); 
        }

    }
}

WebAppMVC_Assignment1/Controllers/TempController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAppMVC_Assignment1.Models;
using Microsoft.AspNetCore.Http;

namespace WebAppMVC_Assignment1.Controllers
{
    public class TempController : Controller
    {
        [HttpGet]
        public IActionResult FeverCheck()
        {
            HttpContext.Session.SetString("View", "Temp/FeverCheck");
            return View();
        }

        [HttpPost]
        public IActionResult FeverCheck(double BodyTemp)
        {
            HttpContext.Session.SetString("View", "Temp/FeverCheck");
            string recommendation=Doctor.giveRecomendation(BodyTemp);

            ViewBag.Recommendation = recommendation;

            //return RedirectToAction(nameof(FeverCheck));
            return View();
        }
    }
}

WebAppMVC_Assignment1/Views/App/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "About";
}

<p>
    <table class="center">
        <tr>
            <td>
                Name
            </td>
            <td>
                Shreya Sai
            </td>
        </tr>
        <tr>
            <td>
                About
            </td>
            <td>
                I am young, vibrant and have a strong enthusiasm in learning different and new types of work which will further enhance my knowledge and skill set.
            </td>
        </tr>
       
    </table>
</p>

WebAppMVC_Assignment1/Views/App/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Contact";
}

<p>
    <table class="center">
        <tr>
            <td>
                Mobile
            </td>
            <td>
                xxxxxxxxx
            </td>
         </tr>
        <tr>
            <td>
                Email ID
            </td>
            <td>
                zzzzzzz@gmail.com
            </td>
        </tr>
    </table>
</p>

WebAppMVC_Assignment1/Views/App/Projects.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Project";
}


<p>
    <h3>GitHub Assignment Links</h3>

    <table class="center">
        <tr>
            <td>
                <a href="https://github.com/ShreyaSai1908/Assignment1-Calculator-.git">Calculator Assigment</a>
            </td>

            <td>
                <h4>Description</h4>
                We got a challenge to make a digital calculator using C# code.
            </td>
         </tr>
         <tr>
            <td>
                <a href="https://github.com/ShreyaSai1908/Assignment2_Hangman.git">Hangman Assignment</a>
            </td>

            <td>
                <h4>Description</h4>
                We got a challenge to make a game using C# coding.
            </td>
        </tr>
    </table>

</p>

WebAppMVC_Assignment1/Views/Game/RandomNumber.cshtml
@model GuessingGame
@{
    ViewBag.Title = "RandomNumber";
}

<div>
    <form asp-action="RandomNumber" method="post">
        <label asp-for="Num"></label>
        <input asp-for="Num" />

        <input type="submit" value="Random Number" />
    </form>
</div>

<div>
    @if (ViewBag.Result != null)
    {

        <p>@ViewBag.Result</p>
        <p>Your Guess:@ViewBag.UserGuess</p>
        <p>Generated Number:@ViewBag.GeneratedNumber</p>
    }
</div>

WebAppMVC_Assignment1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div>
            <img src="~/img/Williams.png" class="center"/>
        </div>        
        <ol>
            <li>
                <!--@Html.ActionLink("about", "About", "App")-->
                <a asp-action="About" asp-controller="App">About</a>
            </li>
            <li>
                <!-- @Html.ActionLink("contact", "Contact", "App") -->
                        <a asp-action="Contact" asp-controller="App">Contact</a>
            </li>
            <li>
                <!-- @Html.ActionLink("projects", "Projects", "App") -->
                <a asp-action="Projects" asp-controller="App">Projects</a>
            </li>

            <li>
                <a asp-action="FeverCheck" asp-controller="Temp">Fever Check</a>

            </li>

            <li>
                <a asp-action="RandomNumber" asp-controller="Game">Guessing Game</a>

            </li>


        </ol>
     </header>
      <div class="center">
                @RenderBody()
      </div>
     
     <div class="footer">
            <p>&#169;Author: Shreya Sai</p>
            <p>@DateTime.Now</p>
     </div>
    </body>
    </html>

WebAppMVC_Assignment1/Views/Temp/FeverCheck.cshtml
@model Doctor
@{
    ViewBag.Title = "FeverCheck";
}

<div>
    <h3>Get your Body Temperature checked here!</h3>
</div>

<div>
    <form asp-action="FeverCheck" method="post">
        <label asp-for="BodyTemp"></label>
        <input asp-for="BodyTemp" />

        <input type="submit" value="Check Fever" />
    </form>
</div>

<div>
    @if (ViewBag.Recommendation != null)
    {
        <p>@ViewBag.Recommendation</p>
    }
</div>